import type { VibeViewerItem } from '@/components/vibeViewer'

export const fakeMediaFileItems: VibeViewerItem[] = [
  {
    id: 'audio-voiceover-cut',
    type: 'audio',
    title: 'Voiceover rough cut',
    extension: 'mp3',
    mimeType: 'audio/mpeg',
    sizeBytes: 3_884_214,
    createdAt: '2026-04-04T07:54:00.000Z',
    durationMs: 186_000,
    original: {
      url: 'https://samplelib.com/lib/preview/mp3/sample-3s.mp3',
      mimeType: 'audio/mpeg',
      sizeBytes: 3_884_214,
    },
  },
  {
    id: 'doc-brand-guidelines',
    type: 'document',
    title: 'Brand guidelines',
    extension: 'pdf',
    mimeType: 'application/pdf',
    sizeBytes: 8_122_019,
    createdAt: '2026-04-04T07:31:00.000Z',
    preview: {
      url: 'https://picsum.photos/id/1033/600/800',
      mimeType: 'image/jpeg',
      sizeBytes: 144_000,
      width: 600,
      height: 800,
    },
    original: {
      url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      mimeType: 'application/pdf',
      sizeBytes: 8_122_019,
    },
  },
  {
    id: 'archive-release-assets',
    type: 'archive',
    title: 'Release assets bundle',
    extension: 'zip',
    mimeType: 'application/zip',
    sizeBytes: 128_000_552,
    createdAt: '2026-04-04T06:30:00.000Z',
    original: {
      url: 'https://example.com/files/release-assets-v03.zip',
      mimeType: 'application/zip',
      sizeBytes: 128_000_552,
    },
  },
  {
    id: 'other-scene-model',
    type: 'other',
    title: 'Trade-show booth model',
    extension: 'glb',
    mimeType: 'model/gltf-binary',
    sizeBytes: 24_805_300,
    createdAt: '2026-04-04T05:46:00.000Z',
    original: {
      url: 'https://example.com/files/trade-show-booth.glb',
      mimeType: 'model/gltf-binary',
      sizeBytes: 24_805_300,
    },
  },
  {
    id: 'audio-field-recording',
    type: 'audio',
    title: 'Field recording ambience',
    extension: 'wav',
    mimeType: 'audio/wav',
    sizeBytes: 34_052_110,
    createdAt: '2026-04-04T05:21:00.000Z',
    durationMs: 441_000,
    original: {
      url: 'https://samplelib.com/lib/preview/wav/sample-6s.wav',
      mimeType: 'audio/wav',
      sizeBytes: 34_052_110,
    },
  },
  {
    id: 'doc-q2-roadmap',
    type: 'document',
    title: 'Q2 roadmap draft',
    extension: 'pptx',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    sizeBytes: 5_240_131,
    createdAt: '2026-04-04T04:36:00.000Z',
    preview: {
      url: 'https://picsum.photos/id/1050/640/360',
      mimeType: 'image/jpeg',
      sizeBytes: 98_000,
      width: 640,
      height: 360,
    },
    original: {
      url: 'https://example.com/files/q2-roadmap-draft.pptx',
      mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      sizeBytes: 5_240_131,
    },
  },
  {
    id: 'other-dataset-export',
    type: 'other',
    title: 'Analytics export',
    extension: 'json',
    mimeType: 'application/json',
    sizeBytes: 1_042_228,
    createdAt: '2026-04-04T03:58:00.000Z',
    original: {
      url: 'https://example.com/files/analytics-export.json',
      mimeType: 'application/json',
      sizeBytes: 1_042_228,
    },
  },
  {
    id: 'audio-notification-pack',
    type: 'audio',
    title: 'Notification pack',
    extension: 'mp3',
    mimeType: 'audio/mpeg',
    sizeBytes: 902_118,
    createdAt: '2026-04-04T03:02:00.000Z',
    durationMs: 49_000,
    original: {
      url: 'https://samplelib.com/lib/preview/mp3/sample-12s.mp3',
      mimeType: 'audio/mpeg',
      sizeBytes: 902_118,
    },
  },
  {
    id: 'doc-legal-brief',
    type: 'document',
    title: 'Vendor legal brief',
    extension: 'docx',
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    sizeBytes: 742_904,
    createdAt: '2026-04-04T02:48:00.000Z',
    original: {
      url: 'https://example.com/files/vendor-legal-brief.docx',
      mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      sizeBytes: 742_904,
    },
  },
  {
    id: 'archive-caption-bundle',
    type: 'archive',
    title: 'Caption exports',
    extension: 'tar',
    mimeType: 'application/x-tar',
    sizeBytes: 18_120_005,
    createdAt: '2026-04-04T01:35:00.000Z',
    original: {
      url: 'https://example.com/files/caption-exports.tar',
      mimeType: 'application/x-tar',
      sizeBytes: 18_120_005,
    },
  },
  {
    id: 'other-copy-deck',
    type: 'other',
    title: 'Campaign copy deck',
    extension: 'md',
    mimeType: 'text/markdown',
    sizeBytes: 42_881,
    createdAt: '2026-04-04T00:49:00.000Z',
    original: {
      url: 'https://example.com/files/campaign-copy-deck.md',
      mimeType: 'text/markdown',
      sizeBytes: 42_881,
    },
  },
  {
    id: 'audio-podcast-note',
    type: 'audio',
    title: 'Podcast chapter note',
    extension: 'mp3',
    mimeType: 'audio/mpeg',
    sizeBytes: 6_204_901,
    createdAt: '2026-04-04T00:14:00.000Z',
    durationMs: 302_000,
    original: {
      url: 'https://samplelib.com/lib/preview/mp3/sample-12s.mp3',
      mimeType: 'audio/mpeg',
      sizeBytes: 6_204_901,
    },
  },
]
