import type { VibeViewerItem } from '@/components/viewer'

const FLOWER_VIDEO_URL = 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4'

export const fakeMediaVisualItems: VibeViewerItem[] = [
  {
    id: 'img-aurora-board',
    type: 'image',
    title: 'Aurora moodboard',
    url: 'https://picsum.photos/id/1015/2400/1600',
    width: 2400,
    height: 1600,
    preview: {
      url: 'https://picsum.photos/id/1015/720/480',
      width: 720,
      height: 480,
    },
  },
  {
    id: 'vid-launch-loop',
    type: 'video',
    title: 'Launch loop teaser',
    url: FLOWER_VIDEO_URL,
    width: 1920,
    height: 1080,
    preview: {
      url: FLOWER_VIDEO_URL,
      width: 640,
      height: 360,
    },
  },
  {
    id: 'img-studio-portrait',
    type: 'image',
    title: 'Studio portrait set',
    url: 'https://picsum.photos/id/1027/1620/2160',
    width: 1620,
    height: 2160,
    preview: {
      url: 'https://picsum.photos/id/1027/540/720',
      width: 540,
      height: 720,
    },
  },
  {
    id: 'vid-dashboard-walkthrough',
    type: 'video',
    title: 'Dashboard walkthrough',
    url: FLOWER_VIDEO_URL,
    width: 2560,
    height: 1440,
    preview: {
      url: FLOWER_VIDEO_URL,
      width: 1280,
      height: 720,
    },
  },
  {
    id: 'img-product-flatlay',
    type: 'image',
    title: 'Product flatlay',
    url: 'https://picsum.photos/id/1060/3040/2026',
    width: 3040,
    height: 2026,
    preview: {
      url: 'https://picsum.photos/id/1060/760/506',
      width: 760,
      height: 506,
    },
  },
  {
    id: 'img-event-wide',
    type: 'image',
    title: 'Event floor panorama',
    url: 'https://picsum.photos/id/1040/2800/1575',
    width: 2800,
    height: 1575,
  },
  {
    id: 'vid-bts-timelapse',
    type: 'video',
    title: 'Behind-the-scenes timelapse',
    url: FLOWER_VIDEO_URL,
    width: 1080,
    height: 1920,
    preview: {
      url: FLOWER_VIDEO_URL,
      width: 540,
      height: 960,
    },
  },
  {
    id: 'img-atlas-cover',
    type: 'image',
    title: 'Atlas cover artwork',
    url: 'https://picsum.photos/id/1003/1800/2700',
    width: 1800,
    height: 2700,
    preview: {
      url: 'https://picsum.photos/id/1003/600/900',
      width: 600,
      height: 900,
    },
  },
  {
    id: 'vid-street-loop',
    type: 'video',
    title: 'Street texture loop',
    url: FLOWER_VIDEO_URL,
    width: 1280,
    height: 720,
    preview: {
      url: FLOWER_VIDEO_URL,
      width: 640,
      height: 360,
    },
  },
  {
    id: 'img-typography-specimen',
    type: 'image',
    title: 'Typography specimen board',
    url: 'https://picsum.photos/id/1039/2040/1530',
    width: 2040,
    height: 1530,
    preview: {
      url: 'https://picsum.photos/id/1039/680/510',
      width: 680,
      height: 510,
    },
  },
  {
    id: 'vid-ui-capture',
    type: 'video',
    title: 'UI interaction capture',
    url: FLOWER_VIDEO_URL,
    width: 1440,
    height: 900,
    preview: {
      url: FLOWER_VIDEO_URL,
      width: 720,
      height: 450,
    },
  },
  {
    id: 'img-missing-proof',
    type: 'image',
    title: 'Missing proof sheet',
    url: '/demo-missing/proof-sheet-404.jpg',
    width: 1920,
    height: 1080,
    preview: {
      url: '/demo-missing/proof-sheet-404.jpg',
      width: 480,
      height: 270,
    },
  },
  {
    id: 'img-broken-preview',
    type: 'image',
    title: 'Broken preview asset',
    url: '/demo-invalid/broken-preview.jpg',
    width: 1600,
    height: 900,
    preview: {
      url: '/demo-invalid/broken-preview.jpg',
      width: 640,
      height: 360,
    },
  },
]
